name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v1
    - name: Run a one-line script
    
    - name: Login to Docker Hub
    - uses: docker/login-action@v1
      with:
          username: "amso98"
          password: "Ismatias_9811"

    - name: install npm
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

    - name: Set up Docker Buildx
      id: buildx
    - uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./vueJS/Dockerfile
          push: true
          tags: amso98/vuejs:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
